### ISSUE TITLE
Question: Instructions?

### ISSUE THREAD

**Issue by ckrozean** [GliaX/pulseox#17]
Are there step-by-step instruction? I purchased parts from the bill of materials with the hope of assembling one of these devices. However, I can't seem to find instructions on how to start.

**Comment by tareko** [comment]
No instructions exist yet. In essence, assemble all parts to their
locations on the board.

Do you have a copy of the PCB made? Perhaps we can work together to make
instructions for others.

tarek : )

**Comment by ckrozean** [comment]
Not at this time. I'm very much new to this. Where can I get a pcb made? 
I would be willing to collaborate on instructions!
Thanks!
Colby Rozean
Texas Tech University – Mechanical Engineering
(806)-831-9391
ckrozean@gmail.com




On Fri, Sep 25, 2015 at 1:22 AM -0700, "Tarek Loubani" <notifications@github.com> wrote:










No instructions exist yet. In essence, assemble all parts to their

locations on the board.



Do you have a copy of the PCB made? Perhaps we can work together to make

instructions for others.



tarek : )

**Comment by tareko** [comment]
Hi Colby,

I'm going to close this for now. If you're still interested, it looks like we're going to have some substantial forward momentum in the next few months, so keep an eye out on the project!
