### ISSUE TITLE
LED circuit

### ISSUE THREAD

**Issue by VojislavM** [GliaX/pulseox#23]
IR LEDs are driven by MCU, which is not a good idea, maybe it is beater to drive them with small H bridge. For example, the diode from BOM is needs 20 mA of forward current, and the STM MCU is able to provide ~20 mA output current source by any I/O and control pin. Is to close, and it may burn the IO Pin of the MCU.

**Comment by kliment** [comment]
The emitters are on for very short pulses, tens of microseconds, so the current limiting is done by PWM. At a supply voltage of 3V the emitters don't reach their rated current even when continuously on, so in practice the current is below even the continuous rated current. We had series limiting resistors on the emitter lines but after measuring the effective current we removed them as they were not necessary. I'd prefer to avoid the extra complexity of an h-bridge, both for BOM cost reasons and to keep the layout single-sided.

**Comment by VojislavM** [comment]
Great, I am glad to hear that you already tested this. I did not know for how long are the LEDs on.
