### ISSUE TITLE
Piezo speaker circuit

### ISSUE THREAD

**Issue by VojislavM** [GliaX/pulseox#25]
Piezo speaker is driven by the MCU pin, which is not a good idea, maybe it is better to drive it with small MOSFET. This is not so problematic because Piezo uses only 1 mA, but it is good practice to use MOSFET.

**Comment by kliment** [comment]
The piezo cannot be driven through a single high or low side FET because it must be both actively charged and actively discharged, so a push-pull configuration is necessary. The currents are very low, the system works well, and the MCU is quite resilient, so I see no reason to add complexity here.

**Comment by VojislavM** [comment]
Ok, I agree.
