### ISSUE TITLE
Power supply circuit

### ISSUE THREAD

**Issue by VojislavM** [GliaX/pulseox#26]
Why are there two power regulators?

**Comment by kliment** [comment]
It's a boost regulator with passthrough to allow operating from a single battery, down to 0.7V, followed by an LDO to allow a 3.3V or 5V supply to be used as well. The operating voltage of the device is 3V.

**Comment by VojislavM** [comment]
I did not know what was the input, but I assumed it was something like that. Thanks for the explanation.
