### ISSUE TITLE
Power connector PCB

### ISSUE THREAD

**Issue by VojislavM** [GliaX/pulseox#27]
Two pin jumper is not the best solution for connecting power to the device. What is the power source for this device and how is it connected?

**Comment by kliment** [comment]
The idea was to solder battery holder wires directly to the pads, rather than use a jumper. The jumper however was very convenient for testing and also has a footprint that is easy to solder wires to.

**Comment by VojislavM** [comment]
That is ok for testing.

**Comment by tareko** [comment]
The end goal here is to allow the device to be connected either via battery or another external supply as able (e.g., wall, other device, etc.)
